<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="7.3.1" />
    <PackageReference Include="MassTransit.Extensions.DependencyInjection" Version="7.3.1" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="7.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\libs\MessageBugLib\Communication.MessageBus.csproj" />
    <ProjectReference Include="..\..\..\Libs\MessageBus\Communication.MessageBus.csproj" />
    <ProjectReference Include="..\BookingService_Domain\BookingService_Domain.csproj" />
    <ProjectReference Include="..\BookingService_Infra\BookingService_Infraestructure.csproj" />
  </ItemGroup>

</Project>
