<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\libs\Communication.Email\Communication.Email.csproj" />
    <ProjectReference Include="..\..\..\libs\MessageBugLib\Communication.MessageBus.csproj" />
    <ProjectReference Include="..\..\..\Libs\MessageBus\Communication.MessageBus.csproj" />
    <ProjectReference Include="..\UserService_Domain\UserService_Domain.csproj" />
    <ProjectReference Include="..\UserService_Infraestructure\UserService_Infraestructure.csproj" />
  </ItemGroup>

</Project>
